name: Dependabot Merge Me!

on:
  pull_request_target:
    branches: [ main ]

jobs:
  merge-me:
    name: Merge me!
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token:  ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          command: squash and merge
